/**
 * Provision (or update) the Auth0 "planet-atlas" application via the Management
 * API, then append the resulting client credentials to `.env.local`.
 *
 * Idempotent: if a `planet-atlas` client already exists it is updated in place
 * (its client_id/secret are reused); otherwise a new `regular_web` app is
 * created. A fresh `AUTH0_SECRET` (32 random bytes, hex) is generated for the
 * cookie encryption key.
 *
 * Run with the user's Management-API M2M credentials in the environment:
 *   AUTH0_MGMT_DOMAIN, AUTH0_MGMT_CLIENT_ID, AUTH0_MGMT_CLIENT_SECRET
 *
 *   pnpm auth0:provision
 *
 * Secrets are NEVER printed — only written to the gitignored `.env.local`.
 */
import { randomBytes } from "node:crypto";
import { appendFile, readFile } from "node:fs/promises";
import path from "node:path";

const APP_NAME = "planet-atlas";

const LOCAL_URL = "http://localhost:3000";
const PROD_URL = "https://global-jade-tau.vercel.app";

const CALLBACKS = [`${LOCAL_URL}/auth/callback`, `${PROD_URL}/auth/callback`];
const LOGOUT_URLS = [LOCAL_URL, PROD_URL];
const WEB_ORIGINS = [LOCAL_URL, PROD_URL];

type Auth0Client = {
  client_id: string;
  client_secret?: string;
  name: string;
};

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required env var ${name}`);
  }
  return value;
}

async function api<T>(
  domain: string,
  token: string,
  method: string,
  route: string,
  body?: unknown,
): Promise<T> {
  const res = await fetch(`https://${domain}${route}`, {
    method,
    headers: {
      authorization: `Bearer ${token}`,
      "content-type": "application/json",
    },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
  if (!res.ok) {
    // Response text may include client detail but never our generated secret.
    throw new Error(
      `Auth0 API ${method} ${route} failed: ${res.status} ${await res.text()}`,
    );
  }
  return (await res.json()) as T;
}

async function getManagementToken(
  domain: string,
  clientId: string,
  clientSecret: string,
): Promise<string> {
  const res = await fetch(`https://${domain}/oauth/token`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      grant_type: "client_credentials",
      client_id: clientId,
      client_secret: clientSecret,
      audience: `https://${domain}/api/v2/`,
    }),
  });
  if (!res.ok) {
    throw new Error(
      `Failed to get Management token: ${res.status} ${await res.text()}`,
    );
  }
  const json = (await res.json()) as { access_token: string };
  return json.access_token;
}

const APP_CONFIG = {
  app_type: "regular_web" as const,
  callbacks: CALLBACKS,
  allowed_logout_urls: LOGOUT_URLS,
  web_origins: WEB_ORIGINS,
  grant_types: ["authorization_code", "refresh_token"],
};

async function upsertClient(
  domain: string,
  token: string,
): Promise<Auth0Client> {
  const existing = await api<Auth0Client[]>(
    domain,
    token,
    "GET",
    "/api/v2/clients?fields=client_id,name&include_fields=true&per_page=100",
  );
  const match = existing.find((c) => c.name === APP_NAME);

  if (match) {
    console.log(`Updating existing "${APP_NAME}" client…`);
    return api<Auth0Client>(
      domain,
      token,
      "PATCH",
      `/api/v2/clients/${encodeURIComponent(match.client_id)}`,
      APP_CONFIG,
    );
  }

  console.log(`Creating new "${APP_NAME}" client…`);
  return api<Auth0Client>(domain, token, "POST", "/api/v2/clients", {
    name: APP_NAME,
    ...APP_CONFIG,
  });
}

async function appendEnvLocal(vars: Record<string, string>): Promise<void> {
  const envPath = path.join(process.cwd(), ".env.local");
  let existing = "";
  try {
    existing = await readFile(envPath, "utf8");
  } catch {
    // File may not exist yet; that's fine.
  }
  const present = new Set(
    existing
      .split("\n")
      .map((line) => line.split("=", 1)[0]?.trim())
      .filter(Boolean),
  );
  const skipped = Object.keys(vars).filter((k) => present.has(k));
  if (skipped.length > 0) {
    console.warn(
      `Note: these keys already exist in .env.local and were NOT overwritten: ${skipped.join(", ")}. Remove them first to rotate.`,
    );
  }
  const toWrite = Object.entries(vars).filter(([k]) => !present.has(k));
  if (toWrite.length === 0) return;

  const block =
    (existing && !existing.endsWith("\n") ? "\n" : "") +
    `\n# Auth0 (generated by pnpm auth0:provision)\n` +
    toWrite.map(([k, v]) => `${k}=${v}`).join("\n") +
    "\n";
  await appendFile(envPath, block, "utf8");
}

async function main(): Promise<void> {
  const mgmtDomain = requireEnv("AUTH0_MGMT_DOMAIN");
  const mgmtClientId = requireEnv("AUTH0_MGMT_CLIENT_ID");
  const mgmtClientSecret = requireEnv("AUTH0_MGMT_CLIENT_SECRET");

  const token = await getManagementToken(
    mgmtDomain,
    mgmtClientId,
    mgmtClientSecret,
  );
  const client = await upsertClient(mgmtDomain, token);

  if (!client.client_secret) {
    throw new Error(
      "Auth0 did not return a client_secret; cannot write .env.local",
    );
  }

  await appendEnvLocal({
    AUTH0_DOMAIN: mgmtDomain,
    AUTH0_CLIENT_ID: client.client_id,
    AUTH0_CLIENT_SECRET: client.client_secret,
    AUTH0_SECRET: randomBytes(32).toString("hex"),
    APP_BASE_URL: LOCAL_URL,
  });

  console.log(
    `Done. "${APP_NAME}" (client_id ${client.client_id}) provisioned; credentials written to .env.local.`,
  );
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
